import Head from "next/head";
import Image from "next/image";
import {
  Card,
  Container,
  Description,
  Footer,
  Grid,
  Main,
  Section,
  Tag,
  Title,
} from "../styles/Home";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Ester Frazão</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Section datatype="light">
          <Tag>Fullstack Developer Jr.</Tag>
          <Title>
            Olá, eu sou <b>Ester Frazão!</b>
          </Title>
          <Description>
            Desenvolvedora web FullStack formada pela Kenzie Academy Brasil, em
            busca de uma posição no mercado de trabalho de tecnologia, com
            conhecimentos em HTML, CSS, Javasvript, React JS, Node Js, Python e
            Django.
          </Description>
        </Section>
        <Section datatype="dark">
          <Grid>
            <Card href="https://nextjs.org/docs">
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </Card>

            <Card href="https://nextjs.org/learn">
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </Card>

            <Card href="https://github.com/vercel/next.js/tree/canary/examples">
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </Card>

            <Card
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </Card>
          </Grid>
        </Section>
      </Main>

      <Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          2022 - <em>Ester Frazão</em> - Web Developer - Todos os direitos reservados | Design por Jackson Carelli
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </Footer>
    </Container>
  );
}
