import Head from "next/head";
import { useRepositories } from "../providers/repositories";
import { Container, Main, Project, ProjectsContainer, Title } from "../styles";
import { BsGithub } from "react-icons/bs";
import { IoLogoVercel } from "react-icons/io5";
import IconButton from "../components/IconButton";
import titleFormatter from "../utils/titleFormatter";
import { ButtonsContainer } from "../styles/About";

export default function Home() {
  const { repositories } = useRepositories();

  return (
    <Container>
      <Head>
        <title>Projetos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>Meus Projetos</Title>
        <ProjectsContainer>
          {repositories?.map((repo) => {
            if (!repo.fork) {
              return (
                <Project key={repo.id}>
                  <h3>{titleFormatter(repo.name)}</h3>
                  <p>{repo.description}</p>
                  <ButtonsContainer style={{ margin: 0 }}>
                    <a
                      href={repo.html_url}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <IconButton icon={<BsGithub />} color="green">
                        Seguir para o repositório
                      </IconButton>
                    </a>
                    {repo.homepage && (
                      <a
                        href={repo.homepage}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        <IconButton icon={<IoLogoVercel />} color="white">
                          Website
                        </IconButton>
                      </a>
                    )}
                  </ButtonsContainer>
                </Project>
              );
            }
          })}
        </ProjectsContainer>
      </Main>
    </Container>
  );
}
